# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "ingress-gateway"

    config.vm.hostname = "ingress-gateway"
  
    config.vm.box = "bento/ubuntu-22.04"
  
    config.vm.box_check_update = true

    config.vm.synced_folder '.', '/vagrant', disabled: true
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine.
    config.vm.network "forwarded_port", guest: 8500, host: 8500
  
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
    end
    
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "playbooks/provisioning.yml"
    end

    config.vm.provision "shell", inline: "echo IP of the VM is $(hostname -I | awk '{print $2}')"

end